import { useEffect } from "react";
import { resetScreenWhenStaleRecords } from "./resetScreenWhenStaleRecords.js";

/** After data loads, clear detail screens when the selected id/name no longer exists in state. */
export function useResetScreenWhenStaleRecords({
  authState,
  screen,
  state,
  selSaleId,
  selCustomerName,
  selVendorName,
  selExpenseId,
  selExpenseCategory,
  selEmiId,
  selBankAccountId,
  selPurchaseId,
  selOtherIncomeId,
  setScreen,
  setSelSaleId,
  setSelCustomerName,
  setSelVendorName,
  setSelExpenseId,
  setSelExpenseCategory,
  setPage,
  setSelEmiId,
  setSelBankAccountId,
  setSelPurchaseId,
  setSelOtherIncomeId,
  onClearGlobalSearchReturn,
  onResetPurchaseNavFromStale,
  onResetEmiNavFromStale,
  onResetSaleNavFromStale,
  onResetOtherIncomeDetailFromStale,
  onResetExpenseNavFromStale,
}) {
  useEffect(() => {
    resetScreenWhenStaleRecords({
      authState,
      screen,
      sales: state.sales,
      expenses: state.expenses,
      emiEntries: state.emiEntries,
      customerDirectory: state.customerDirectory,
      vendorDirectory: state.vendorDirectory,
      bankAccounts: state.balance?.bankAccounts,
      purchases: state.purchases,
      selSaleId,
      selCustomerName,
      selVendorName,
      selExpenseId,
      selExpenseCategory,
      selEmiId,
      selBankAccountId,
      selPurchaseId,
      selOtherIncomeId,
      setScreen,
      setSelSaleId,
      setSelCustomerName,
      setSelVendorName,
      setSelExpenseId,
      setSelExpenseCategory,
      setPage,
      setSelEmiId,
      setSelBankAccountId,
      setSelPurchaseId,
      setSelOtherIncomeId,
      otherIncomes: state.otherIncomes,
      onClearGlobalSearchReturn,
      onResetPurchaseNavFromStale,
      onResetEmiNavFromStale,
      onResetSaleNavFromStale,
      onResetOtherIncomeDetailFromStale,
      onResetExpenseNavFromStale,
    });
  }, [
    authState,
    screen,
    selSaleId,
    selExpenseId,
    selExpenseCategory,
    selCustomerName,
    selVendorName,
    selEmiId,
    selBankAccountId,
    selPurchaseId,
    selOtherIncomeId,
    state.sales,
    state.expenses,
    state.emiEntries,
    state.customerDirectory,
    state.vendorDirectory,
    state.balance?.bankAccounts,
    state.purchases,
    setScreen,
    setSelSaleId,
    setSelCustomerName,
    setSelVendorName,
    setSelExpenseId,
    setSelExpenseCategory,
    setPage,
    setSelEmiId,
    setSelBankAccountId,
    setSelPurchaseId,
    setSelOtherIncomeId,
    state.otherIncomes,
    onClearGlobalSearchReturn,
    onResetPurchaseNavFromStale,
    onResetEmiNavFromStale,
    onResetSaleNavFromStale,
    onResetOtherIncomeDetailFromStale,
    onResetExpenseNavFromStale,
  ]);
}
